import type { ModuleRuntimeConfig, NitroUrlResolvers, SitemapIndexEntry } from '../../../types'
import { withQuery } from 'ufo'
import { createChunkedXmlStream } from '../stream'
import { escapeValueForXml } from './xml'

export function* renderSitemapIndexXmlChunks(sitemaps: SitemapIndexEntry[], resolvers: NitroUrlResolvers, { version, xsl, credits, minify }: Pick<ModuleRuntimeConfig, 'version' | 'xsl' | 'credits' | 'minify'>, errorInfo?: { messages: string[], urls: string[] }): Generator<string> {
  const NL = minify ? '' : '\n'
  const I1 = minify ? '' : '    '
  const I2 = minify ? '' : '        '

  yield '<?xml version="1.0" encoding="UTF-8"?>'

  if (xsl) {
    let relativeBaseUrl = resolvers.relativeBaseUrlResolver?.(xsl) ?? xsl
    if (errorInfo && errorInfo.messages.length > 0) {
      relativeBaseUrl = withQuery(relativeBaseUrl, {
        errors: 'true',
        error_messages: errorInfo.messages,
        error_urls: errorInfo.urls,
      })
    }
    yield `${NL}<?xml-stylesheet type="text/xsl" href="${escapeValueForXml(relativeBaseUrl)}"?>`
  }

  yield `${NL}<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${NL}`
  for (let i = 0; i < sitemaps.length; i++) {
    const entry = sitemaps[i]!
    if (i > 0)
      yield NL
    yield `${I1}<sitemap>${NL}${I2}<loc>${escapeValueForXml(entry.sitemap)}</loc>${NL}`
    if (entry.lastmod)
      yield `${I2}<lastmod>${escapeValueForXml(entry.lastmod)}</lastmod>${NL}`
    yield `${I1}</sitemap>`
  }
  yield `${NL}</sitemapindex>`

  if (credits)
    yield `${NL}<!-- XML Sitemap Index generated by @nuxtjs/sitemap v${version} at ${new Date().toISOString()} -->`
}

export function urlsToIndexXml(sitemaps: SitemapIndexEntry[], resolvers: NitroUrlResolvers, config: Pick<ModuleRuntimeConfig, 'version' | 'xsl' | 'credits' | 'minify'>, errorInfo?: { messages: string[], urls: string[] }) {
  let xml = ''
  for (const chunk of renderSitemapIndexXmlChunks(sitemaps, resolvers, config, errorInfo))
    xml += chunk
  return xml
}

export function urlsToIndexXmlStream(sitemaps: SitemapIndexEntry[], resolvers: NitroUrlResolvers, config: Pick<ModuleRuntimeConfig, 'version' | 'xsl' | 'credits' | 'minify'>, errorInfo?: { messages: string[], urls: string[] }): ReadableStream<Uint8Array> {
  return createChunkedXmlStream(renderSitemapIndexXmlChunks(sitemaps, resolvers, config, errorInfo))
}
