import type { ModuleRuntimeConfig, NitroUrlResolvers, SitemapIndexEntry } from '../../../types'
import { withQuery } from 'ufo'
import { createChunkedXmlStream } from '../stream'
import { escapeValueForXml } from './xml'

function resolveIndexXslHref(resolvers: NitroUrlResolvers, xsl: string, errorInfo?: { messages: string[], urls: string[] }) {
  let relativeBaseUrl = resolvers.relativeBaseUrlResolver?.(xsl) ?? xsl
  if (errorInfo && errorInfo.messages.length > 0) {
    relativeBaseUrl = withQuery(relativeBaseUrl, {
      errors: 'true',
      error_messages: errorInfo.messages,
      error_urls: errorInfo.urls,
    })
  }
  return relativeBaseUrl
}

export function* renderSitemapIndexXmlChunks(sitemaps: SitemapIndexEntry[], resolvers: NitroUrlResolvers, { version, xsl, credits, minify }: Pick<ModuleRuntimeConfig, 'version' | 'xsl' | 'credits' | 'minify'>, errorInfo?: { messages: string[], urls: string[] }): Generator<string> {
  const NL = minify ? '' : '\n'
  const I1 = minify ? '' : '    '
  const I2 = minify ? '' : '        '

  yield '<?xml version="1.0" encoding="UTF-8"?>'

  if (xsl) {
    const relativeBaseUrl = resolveIndexXslHref(resolvers, xsl, errorInfo)
    yield `${NL}<?xml-stylesheet type="text/xsl" href="${escapeValueForXml(relativeBaseUrl)}"?>`
  }

  yield `${NL}<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${NL}`
  for (let i = 0; i < sitemaps.length; i++) {
    const entry = sitemaps[i]!
    if (i > 0)
      yield NL
    yield `${I1}<sitemap>${NL}${I2}<loc>${escapeValueForXml(entry.sitemap)}</loc>${NL}`
    if (entry.lastmod)
      yield `${I2}<lastmod>${escapeValueForXml(entry.lastmod)}</lastmod>${NL}`
    yield `${I1}</sitemap>`
  }
  yield `${NL}</sitemapindex>`

  if (credits)
    yield `${NL}<!-- XML Sitemap Index generated by @nuxtjs/sitemap v${version} at ${new Date().toISOString()} -->`
}

export function urlsToIndexXml(sitemaps: SitemapIndexEntry[], resolvers: NitroUrlResolvers, { version, xsl, credits, minify }: Pick<ModuleRuntimeConfig, 'version' | 'xsl' | 'credits' | 'minify'>, errorInfo?: { messages: string[], urls: string[] }) {
  const NL = minify ? '' : '\n'
  const I1 = minify ? '' : '    '
  const I2 = minify ? '' : '        '
  let sitemapXml = ''
  for (const entry of sitemaps) {
    if (sitemapXml)
      sitemapXml += NL
    sitemapXml += `${I1}<sitemap>${NL}${I2}<loc>${escapeValueForXml(entry.sitemap)}</loc>${NL}`
    if (entry.lastmod)
      sitemapXml += `${I2}<lastmod>${escapeValueForXml(entry.lastmod)}</lastmod>${NL}`
    sitemapXml += `${I1}</sitemap>`
  }

  const xmlParts = ['<?xml version="1.0" encoding="UTF-8"?>']

  if (xsl) {
    const relativeBaseUrl = resolveIndexXslHref(resolvers, xsl, errorInfo)
    xmlParts.push(`<?xml-stylesheet type="text/xsl" href="${escapeValueForXml(relativeBaseUrl)}"?>`)
  }

  xmlParts.push(
    '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    sitemapXml,
    '</sitemapindex>',
  )

  if (credits)
    xmlParts.push(`<!-- XML Sitemap Index generated by @nuxtjs/sitemap v${version} at ${new Date().toISOString()} -->`)

  return xmlParts.join(NL)
}

export function urlsToIndexXmlStream(sitemaps: SitemapIndexEntry[], resolvers: NitroUrlResolvers, config: Pick<ModuleRuntimeConfig, 'version' | 'xsl' | 'credits' | 'minify'>, errorInfo?: { messages: string[], urls: string[] }): ReadableStream<Uint8Array> {
  return createChunkedXmlStream(renderSitemapIndexXmlChunks(sitemaps, resolvers, config, errorInfo))
}
