import { describe, expect, it } from 'vitest'
import { createResolver } from '@nuxt/kit'
import { $fetch, setup } from '@nuxt/test-utils'

const { resolve } = createResolver(import.meta.url)

await setup({
  rootDir: resolve('../.playground'),
  build: true,
  server: true,
  nuxtConfig: {
    app: {
      baseURL: '/base',
    },
    sitemap: {
      autoLastmod: false,
      siteUrl: 'https://nuxt-simple-sitemap.com',
    },
  },
})
describe('base', () => {
  it('basic', async () => {
    const sitemapIndex = await $fetch('/base/sitemap_index.xml')

    // test that we have 2 sitemap entries using regex
    expect(sitemapIndex.match(/<sitemap>/g)!.length).toBe(2)

    expect(sitemapIndex).not.match(/\/base\/base\//g)

    const posts = await $fetch('/base/posts-sitemap.xml')

    // expect(posts).not.match(/\/base\/base\//g)
    expect(posts).toMatchInlineSnapshot(`
      "<?xml version=\\"1.0\\" encoding=\\"UTF-8\\"?><?xml-stylesheet type=\\"text/xsl\\" href=\\"/base/__sitemap__/style.xsl\\"?>
      <urlset xmlns:xsi=\\"http://www.w3.org/2001/XMLSchema-instance\\" xmlns:xhtml=\\"http://www.w3.org/1999/xhtml\\" xmlns:image=\\"http://www.google.com/schemas/sitemap-image/1.1\\" xsi:schemaLocation=\\"http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd\\" xmlns=\\"http://www.sitemaps.org/schemas/sitemap/0.9\\">
          <url>
              <loc>http://127.0.0.1:37275/base/blog</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/blog\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/blog/tags</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/blog/tags\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/blog/post-1</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/blog/post-1\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/blog/post-2</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/blog/post-2\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/blog/post-3</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/blog/post-3\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/blog/post-4</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/blog/post-4\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/blog/post-5</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/blog/post-5\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/blog/tags/new</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/blog/tags/new\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/blog/tags/edit</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/blog/tags/edit\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/blog/categories</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/blog/categories\\" />
          </url>
      </urlset>
      <!-- XML Sitemap generated by Nuxt Simple Sitemap -->"
    `)

    expect(await $fetch('/base/pages-sitemap.xml')).toMatchInlineSnapshot(`
      "<?xml version=\\"1.0\\" encoding=\\"UTF-8\\"?><?xml-stylesheet type=\\"text/xsl\\" href=\\"/base/__sitemap__/style.xsl\\"?>
      <urlset xmlns:xsi=\\"http://www.w3.org/2001/XMLSchema-instance\\" xmlns:xhtml=\\"http://www.w3.org/1999/xhtml\\" xmlns:image=\\"http://www.google.com/schemas/sitemap-image/1.1\\" xsi:schemaLocation=\\"http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd\\" xmlns=\\"http://www.sitemaps.org/schemas/sitemap/0.9\\">
          <url>
              <loc>http://127.0.0.1:37275/base</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/!</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/!\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/D</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/D\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/O</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/O\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/C</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/C\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/T</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/T\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/Y</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/Y\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/P</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/P\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/E</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/E\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/h</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/h\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/t</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/t\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/m</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/m\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/l</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/l\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/e</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/e\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/a</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/a\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/d</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/d\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/c</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/c\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/r</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/r\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/s</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/s\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/=</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/=\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/u</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/u\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/f</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/f\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/-</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/-\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/8</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/8\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/n</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/n\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/v</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/v\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/i</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/i\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/w</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/w\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/p</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/p\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/o</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/o\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/,</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/,\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/1</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/1\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/k</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/k\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/g</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/g\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/b</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/b\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/_</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/_\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/x</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/x\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/y</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/y\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/.</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/.\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/2</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/2\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/9</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/9\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/j</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/j\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/7</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/7\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/0</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/0\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/4</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/4\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/5</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/5\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/3</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/3\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/6</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/6\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/&</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/&\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/q</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/q\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/;</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/;\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/N</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/N\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/U</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/U\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/X</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/X\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/(</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/(\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/)</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/)\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/:</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/:\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/$</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/$\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/B</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/B\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/F</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/F\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/R</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/R\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/L</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/L\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/Q</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/Q\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/I</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/I\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/S</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/S\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/V</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/V\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/A</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/A\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/%3C</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/%253C\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/%20</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/%2520\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/%3E</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/%253E\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/%0A</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/%250A\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/%22</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/%2522\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/%5B</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/%255B\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/%5D</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/%255D\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/%7B</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/%257B\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/%7D</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/%257D\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/%5C</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/%255C\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/bar</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/bar\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/foo</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/foo\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/about</loc>
              <lastmod>2023-02-21T08:50:52+00:00</lastmod>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/about\\" />
              <image:image>
                  <image:loc>https://example.com/image-3.jpg</image:loc>
              </image:image>
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/secret</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/secret\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/new-page</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/new-page\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/users-lazy/1</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/users-lazy/1\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/users-lazy/2</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/users-lazy/2\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/users-lazy/3</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/users-lazy/3\\" />
          </url>
          <url>
              <loc>http://127.0.0.1:37275/base/hidden-path-but-in-sitemap</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"http://127.0.0.1:37275/base/fr/hidden-path-but-in-sitemap\\" />
          </url>
      </urlset>
      <!-- XML Sitemap generated by Nuxt Simple Sitemap -->"
    `)
  }, 60000)
})
