import { readFile } from 'node:fs/promises'
import { describe, expect, it } from 'vitest'
import { buildNuxt, createResolver, loadNuxt } from '@nuxt/kit'

describe('generate', () => {
  it('basic', async () => {
    process.env.NODE_ENV = 'production'
    process.env.prerender = true
    const { resolve } = createResolver(import.meta.url)
    const rootDir = resolve('../.playground')
    const nuxt = await loadNuxt({
      rootDir,
      overrides: {
        _generate: true,
        sitemap: {
          autoLastmod: false,
        },
      },
    })

    await buildNuxt(nuxt)

    await new Promise(resolve => setTimeout(resolve, 1000))

    const sitemap = await readFile(resolve(rootDir, '.output/public/sitemap_index.xml'), 'utf-8')
    expect(sitemap).toMatchInlineSnapshot(`
      "<?xml version=\\"1.0\\" encoding=\\"UTF-8\\"?><?xml-stylesheet type=\\"text/xsl\\" href=\\"/__sitemap__/style.xsl\\"?>
      <sitemapindex xmlns=\\"http://www.sitemaps.org/schemas/sitemap/0.9\\">
          <sitemap>
              <loc>http://localhost:3000/posts-sitemap.xml</loc>
          </sitemap>
          <sitemap>
              <loc>http://localhost:3000/pages-sitemap.xml</loc>
              <lastmod>2023-02-21T08:50:52+00:00</lastmod>
          </sitemap>
      </sitemapindex>
      <!-- XML Sitemap generated by Nuxt Simple Sitemap -->"
    `)

    const pages = await readFile(resolve(rootDir, '.output/public/pages-sitemap.xml'), 'utf-8')
    expect(pages).toMatchInlineSnapshot(`
      "<?xml version=\\"1.0\\" encoding=\\"UTF-8\\"?><?xml-stylesheet type=\\"text/xsl\\" href=\\"/__sitemap__/style.xsl\\"?>
      <urlset xmlns:xsi=\\"http://www.w3.org/2001/XMLSchema-instance\\" xmlns:image=\\"http://www.google.com/schemas/sitemap-image/1.1\\" xsi:schemaLocation=\\"http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd\\" xmlns=\\"http://www.sitemaps.org/schemas/sitemap/0.9\\">
          <url>
              <loc>http://localhost:3000</loc>
          </url>
          <url>
              <loc>http://localhost:3000/about</loc>
              <image:image>
                  <image:url>https://res.cloudinary.com/dl6o1xpyq/image/upload/f_jpg,q_auto:best,dpr_auto,w_240,h_240/images/harlan-wilton</image:url>
              </image:image>
              <lastmod>2023-02-21T08:50:52+00:00</lastmod>
              <changefreq>daily</changefreq>
              <priority>0.3</priority>
          </url>
          <url>
              <loc>http://localhost:3000/users-lazy/1</loc>
          </url>
          <url>
              <loc>http://localhost:3000/users-lazy/2</loc>
          </url>
          <url>
              <loc>http://localhost:3000/users-lazy/3</loc>
          </url>
          <url>
              <loc>http://localhost:3000/users-prerender</loc>
          </url>
          <url>
              <loc>http://localhost:3000/hidden-path-but-in-sitemap</loc>
          </url>
      </urlset>
      <!-- XML Sitemap generated by Nuxt Simple Sitemap -->"
    `)
  }, 60000)
})
