import { describe, expect, it } from 'vitest'
import { createResolver } from '@nuxt/kit'
import { $fetch, setup } from '@nuxt/test-utils'

const { resolve } = createResolver(import.meta.url)

await setup({
  rootDir: resolve('../.playground'),
  build: true,
  server: true,
  nuxtConfig: {
    i18n: {
      pages: {
        'about': {
          en: '/about',
          fr: '/a-propos',
        },
        'services/index': {
          en: '/services',
          fr: '/offres',
        },
        'services/development/index': {
          en: '/services/development',
          fr: '/offres/developement',
        },
        'services/development/app/index': {
          en: '/services/development/app',
          fr: '/offres/developement/app',
        },
        'services/development/website/index': {
          en: '/services/development/website',
          fr: '/offres/developement/site-web',
        },
        'services/coaching/index': {
          en: '/services/coaching',
          fr: '/offres/formation',
        },
      },
    },
    sitemap: {
      autoLastmod: false,
      siteUrl: 'https://nuxt-simple-sitemap.com',
    },
  },
})
describe('i18n', () => {
  it('basic', async () => {
    let posts = await $fetch('/posts-sitemap.xml')

    // strip lastmod
    posts = posts.replace(/<lastmod>.*<\/lastmod>/g, '')

    expect(posts).toMatchInlineSnapshot(`
      "<?xml version=\\"1.0\\" encoding=\\"UTF-8\\"?><?xml-stylesheet type=\\"text/xsl\\" href=\\"/__sitemap__/style.xsl\\"?>
      <urlset xmlns:xsi=\\"http://www.w3.org/2001/XMLSchema-instance\\" xmlns:xhtml=\\"http://www.w3.org/1999/xhtml\\" xmlns:image=\\"http://www.google.com/schemas/sitemap-image/1.1\\" xsi:schemaLocation=\\"http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd\\" xmlns=\\"http://www.sitemaps.org/schemas/sitemap/0.9\\">
          <url>
              <loc>https://nuxt-simple-sitemap.com/blog/post-1</loc>
          </url>
          <url>
              <loc>https://nuxt-simple-sitemap.com/blog/post-2</loc>
          </url>
          <url>
              <loc>https://nuxt-simple-sitemap.com/blog/post-3</loc>
          </url>
          <url>
              <loc>https://nuxt-simple-sitemap.com/blog/post-4</loc>
          </url>
          <url>
              <loc>https://nuxt-simple-sitemap.com/blog/post-5</loc>
          </url>
      </urlset>
      <!-- XML Sitemap generated by Nuxt Simple Sitemap -->"
    `)

    expect((await $fetch('/pages-sitemap.xml')).replace(/<lastmod>.*<\/lastmod>/g, '')).toMatchInlineSnapshot(`
      "<?xml version=\\"1.0\\" encoding=\\"UTF-8\\"?><?xml-stylesheet type=\\"text/xsl\\" href=\\"/__sitemap__/style.xsl\\"?>
      <urlset xmlns:xsi=\\"http://www.w3.org/2001/XMLSchema-instance\\" xmlns:xhtml=\\"http://www.w3.org/1999/xhtml\\" xmlns:image=\\"http://www.google.com/schemas/sitemap-image/1.1\\" xsi:schemaLocation=\\"http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd\\" xmlns=\\"http://www.sitemaps.org/schemas/sitemap/0.9\\">
          <url>
              <loc>https://nuxt-simple-sitemap.com</loc>
          </url>
          <url>
              <loc>https://nuxt-simple-sitemap.com/bar</loc>
          </url>
          <url>
              <loc>https://nuxt-simple-sitemap.com/foo</loc>
          </url>
          <url>
              <loc>https://nuxt-simple-sitemap.com/about</loc>
              
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"https://nuxt-simple-sitemap.com/fr/a-propos\\" />
              <xhtml:link rel=\\"alternate\\" href=\\"https://nuxt-simple-sitemap.com/fr/about\\" hreflang=\\"fr\\" />
              <image:image>
                  <image:loc>https://example.com/image.jpg</image:loc>
              </image:image>
              <image:image>
                  <image:loc>https://example.com/image2.jpg</image:loc>
              </image:image>
              <image:image>
                  <image:loc>https://example.com/image-3.jpg</image:loc>
              </image:image>
              <changefreq>daily</changefreq>
              <priority>0.3</priority>
          </url>
          <url>
              <loc>https://nuxt-simple-sitemap.com/services</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"https://nuxt-simple-sitemap.com/fr/offres\\" />
          </url>
          <url>
              <loc>https://nuxt-simple-sitemap.com/users-lazy/1</loc>
          </url>
          <url>
              <loc>https://nuxt-simple-sitemap.com/users-lazy/2</loc>
          </url>
          <url>
              <loc>https://nuxt-simple-sitemap.com/users-lazy/3</loc>
          </url>
          <url>
              <loc>https://nuxt-simple-sitemap.com/users-prerender</loc>
          </url>
          <url>
              <loc>https://nuxt-simple-sitemap.com/services/coaching</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"https://nuxt-simple-sitemap.com/fr/offres/formation\\" />
          </url>
          <url>
              <loc>https://nuxt-simple-sitemap.com/services/development</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"https://nuxt-simple-sitemap.com/fr/offres/developement\\" />
          </url>
          <url>
              <loc>https://nuxt-simple-sitemap.com/services/development/app</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"https://nuxt-simple-sitemap.com/fr/offres/developement/app\\" />
          </url>
          <url>
              <loc>https://nuxt-simple-sitemap.com/services/development/website</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"https://nuxt-simple-sitemap.com/fr/offres/developement/site-web\\" />
          </url>
      </urlset>
      <!-- XML Sitemap generated by Nuxt Simple Sitemap -->"
    `)
  }, 60000)
})
