import { describe, expect, it } from 'vitest'
import { createResolver } from '@nuxt/kit'
import { $fetch, setup } from '@nuxt/test-utils'

const { resolve } = createResolver(import.meta.url)

await setup({
  rootDir: resolve('../.playground'),
  build: true,
  server: true,
  nuxtConfig: {
    sitemap: {
      sitemaps: false,
      sitemapName: 'test.xml',
      siteUrl: 'https://nuxtseo.com',
    },
  },
})
describe('sitemapName', () => {
  it('basic', async () => {
    const sitemap = await $fetch('/test.xml')
    // basic test to make sure we get a valid response
    expect(sitemap).toMatchInlineSnapshot(`
      "<?xml version=\\"1.0\\" encoding=\\"UTF-8\\"?><?xml-stylesheet type=\\"text/xsl\\" href=\\"/__sitemap__/style.xsl\\"?>
      <urlset xmlns:xsi=\\"http://www.w3.org/2001/XMLSchema-instance\\" xmlns:video=\\"http://www.google.com/schemas/sitemap-video/1.1\\" xmlns:xhtml=\\"http://www.w3.org/1999/xhtml\\" xmlns:image=\\"http://www.google.com/schemas/sitemap-image/1.1\\" xsi:schemaLocation=\\"http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd http://www.google.com/schemas/sitemap-image/1.1 http://www.google.com/schemas/sitemap-image/1.1/sitemap-image.xsd\\" xmlns=\\"http://www.sitemaps.org/schemas/sitemap/0.9\\">
          <url>
              <loc>https://nuxtseo.com/about</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"https://nuxtseo.com/fr/a-propos\\" />
              <lastmod>2023-02-20T21:50:52+00:00</lastmod>
              <changefreq>daily</changefreq>
              <priority>0.3</priority>
              <image:image>
                  <image:loc>https://nuxtseo.com/image.jpg</image:loc>
              </image:image>
              <image:image>
                  <image:loc>https://nuxtseo.com/image2.jpg</image:loc>
              </image:image>
          </url>
          <url>
              <loc>https://nuxtseo.com/services</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"https://nuxtseo.com/fr/offres\\" />
          </url>
          <url>
              <loc>https://nuxtseo.com/blog/post-1</loc>
          </url>
          <url>
              <loc>https://nuxtseo.com/blog/post-2</loc>
          </url>
          <url>
              <loc>https://nuxtseo.com/blog/post-3</loc>
          </url>
          <url>
              <loc>https://nuxtseo.com/blog/post-4</loc>
          </url>
          <url>
              <loc>https://nuxtseo.com/blog/post-5</loc>
          </url>
          <url>
              <loc>https://nuxtseo.com/users-lazy/1</loc>
          </url>
          <url>
              <loc>https://nuxtseo.com/users-lazy/2</loc>
          </url>
          <url>
              <loc>https://nuxtseo.com/users-lazy/3</loc>
          </url>
          <url>
              <loc>https://nuxtseo.com/services/coaching</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"https://nuxtseo.com/fr/offres/formation\\" />
          </url>
          <url>
              <loc>https://nuxtseo.com/services/development</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"https://nuxtseo.com/fr/offres/developement\\" />
          </url>
          <url>
              <loc>https://nuxtseo.com/services/development/app</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"https://nuxtseo.com/fr/offres/developement/app\\" />
          </url>
          <url>
              <loc>https://nuxtseo.com/services/development/website</loc>
              <xhtml:link rel=\\"alternate\\" hreflang=\\"fr\\" href=\\"https://nuxtseo.com/fr/offres/developement/site-web\\" />
          </url>
      </urlset>
      <!-- XML Sitemap generated by Nuxt Simple Sitemap -->"
    `)
    expect(sitemap).toContain('<loc>https://nuxtseo.com/</loc>')
  }, 60000)
})
