blockExoticSubdeps: false

minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - nuxtseo-layer-devtools
  - nuxtseo-shared
  - nuxt-site-config-kit
  - nuxt-site-config
  - site-config-stack
  - '@nuxt/kit@4.6.0'
  - '@nuxt/nitro-server@4.6.0'
  - '@nuxt/schema@4.6.0'
  - '@nuxt/vite-builder@4.6.0'
  - nuxt@4.6.0
  - '@harlan-zw/comark-content@0.2.0'
  - '@nuxt/cli@4.0.0'
  - '@nuxt/vite-server@4.6.0'
  - '@nuxt/devtools-kit@4.0.0-beta.4'
  - vite@8.3.3

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 262800

trustPolicyExclude:
  - stylehacks@9.0.7
  - postcss-unique-selectors@9.0.5
  - postcss-svgo@9.0.4
  - postcss-reduce-transforms@9.0.4
  - postcss-reduce-initial@9.0.6
  - postcss-ordered-values@9.0.6
  - postcss-normalize-whitespace@9.0.5
  - postcss-normalize-url@9.0.5
  - postcss-normalize-unicode@9.0.5
  - postcss-normalize-timing-functions@9.0.5
  - postcss-normalize-string@9.0.5
  - postcss-normalize-repeat-style@9.0.5
  - postcss-normalize-positions@9.0.6
  - postcss-normalize-display-values@9.0.5
  - postcss-normalize-charset@9.0.5
  - postcss-minify-selectors@9.0.6
  - postcss-minify-params@9.0.6
  - postcss-minify-gradients@9.0.6
  - postcss-minify-font-values@9.0.7
  - postcss-merge-rules@9.0.8
  - postcss-merge-longhand@9.2.0
  - postcss-discard-overridden@9.0.5
  - postcss-discard-empty@9.0.5
  - postcss-discard-duplicates@9.0.5
  - postcss-discard-comments@9.0.6
  - postcss-convert-values@9.0.7
  - postcss-colormin@9.0.6
  - cssnano-utils@8.1.0
  - cssnano-preset-default@9.2.2
  - cssnano@9.2.2
  - chokidar
  - semver

shellEmulator: true

packages:
  - packages/*
  - devtools
  - test/fixtures/**
  - '!test/fixtures/nuxt5'
  - '!test/fixtures/nuxt46'
  - playground
  - benchmark
  - '!examples/**'

overrides:
  '@nuxtjs/robots': https://pkg.pr.new/nuxt-modules/robots/@nuxtjs/robots@24f4dcdbf3cd8d4c19a210b62eec8295eb4772a7
  '@vitejs/plugin-vue': ^6.0.8
  cssnano: 9.2.2
  cssnano-preset-default: 9.2.2
  cssnano-utils: 8.1.0
  nuxt-site-config: https://pkg.pr.new/harlan-zw/nuxt-site-config/nuxt-site-config@59e27b8dc55b21407ce19dfdbb7be0c6571e9490
  nuxt-site-config-kit: https://pkg.pr.new/harlan-zw/nuxt-site-config/nuxt-site-config-kit@59e27b8dc55b21407ce19dfdbb7be0c6571e9490
  nuxtseo-shared: https://pkg.pr.new/harlan-zw/nuxt-seo/nuxtseo-shared@226c091a0744b7286ef721ac035eed53856bfaa5

  postcss-calc: 11.2.2
  postcss-colormin: 9.0.6
  postcss-convert-values: 9.0.7
  postcss-discard-comments: 9.0.6
  postcss-discard-duplicates: 9.0.5
  postcss-discard-empty: 9.0.5
  postcss-discard-overridden: 9.0.5
  postcss-merge-longhand: 9.2.0
  postcss-merge-rules: 9.0.8
  postcss-minify-font-values: 9.0.7
  postcss-minify-gradients: 9.0.6
  postcss-minify-params: 9.0.6
  postcss-minify-selectors: 9.0.6
  postcss-normalize-charset: 9.0.5
  postcss-normalize-display-values: 9.0.5
  postcss-normalize-positions: 9.0.6
  postcss-normalize-repeat-style: 9.0.5
  postcss-normalize-string: 9.0.5
  postcss-normalize-timing-functions: 9.0.5
  postcss-normalize-unicode: 9.0.5
  postcss-normalize-url: 9.0.5
  postcss-normalize-whitespace: 9.0.5
  postcss-ordered-values: 9.0.6
  postcss-reduce-initial: 9.0.6
  postcss-reduce-transforms: 9.0.4
  postcss-svgo: 9.0.4
  postcss-unique-selectors: 9.0.5
  site-config-stack: https://pkg.pr.new/harlan-zw/nuxt-site-config/site-config-stack@59e27b8dc55b21407ce19dfdbb7be0c6571e9490
  stylehacks: 9.0.7
  vite: ^8.3.3

patchedDependencies:
  '@nuxtjs/mdc': patches/@nuxtjs__mdc.patch

allowBuilds:
  '@firebase/util': false
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  protobufjs: false
  simple-git-hooks: false
  unrs-resolver: false
  vue-demi: true
  workerd: false

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild

catalog:
  '@antfu/eslint-config': ^9.5.1
  '@arethetypeswrong/cli': ^0.18.5
  '@harlan-zw/comark-content': ^0.2.0
  '@nuxt/content': ^3.16.1
  '@nuxt/devtools-kit': 4.0.0-beta.4
  '@nuxt/kit': ^4.6.0
  '@nuxt/module-builder': ^1.0.3
  '@nuxt/test-utils': ^4.3.3
  '@nuxt/ui': ^4.11.3
  '@nuxtjs/i18n': ^10.6.0
  '@nuxtjs/robots': ^7.0.0
  '@vue/test-utils': ^2.5.1
  autocannon: ^8.0.0
  better-sqlite3: ^13.0.3
  bumpp: ^12.3.0
  consola: ^3.4.2
  defu: ^6.1.7
  eslint: ^10.12.0
  eslint-plugin-harlanzw: ^0.23.0
  fast-xml-parser: ^5.11.2
  happy-dom: ^20.14.5
  nuxt: ^4.6.0
  nuxt-i18n-micro: ^3.30.0
  nuxt-site-config: ^5.0.0
  nuxtseo-layer-devtools: ^5.3.16
  nuxtseo-shared: ^6.0.0
  ofetch: ^1.5.1
  oxc-parser: ^0.153.0
  oxc-walker: ^1.1.1
  radix3: ^1.1.2
  std-env: ^4.3.0
  typescript: 6.0.3
  ufo: ^1.6.4
  ultrahtml: ^1.7.0
  unbuild: ^3.6.1
  vitest: ^5.0.3
  vue: ^3.5.43
  vue-tsc: ^3.3.12
  zod: ^4.6.5
