minimumReleaseAgeExclude:
  - '@iconify-json/simple-icons@1.2.86'
  - '@vue/language-core@3.3.4'
  - semver@7.8.3
  - vue-tsc@3.3.4
  - nuxtseo-layer-devtools
  - nuxtseo-shared
shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar
  - semver
packages:
  - devtools
  - test/fixtures/**
  - playground
  - benchmark
  - '!examples/**'
overrides:
  '@vitejs/plugin-vue': ^6.0.7
  vite: ^8.0.16
patchedDependencies:
  '@nuxtjs/mdc': patches/@nuxtjs__mdc.patch
catalog:
  '@antfu/eslint-config': ^9.0.0
  '@arethetypeswrong/cli': ^0.18.3
  '@nuxt/content': ^3.14.0
  '@nuxt/devtools-kit': 4.0.0-alpha.3
  '@nuxt/kit': ^4.4.8
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/test-utils': ^4.0.3
  '@nuxt/ui': ^4.8.2
  '@nuxtjs/i18n': ^10.4.0
  '@nuxtjs/robots': ^6.0.9
  '@vue/test-utils': ^2.4.11
  autocannon: ^8.0.0
  better-sqlite3: ^12.10.0
  bumpp: ^11.1.0
  consola: ^3.4.2
  defu: ^6.1.7
  eslint: ^10.4.1
  eslint-plugin-harlanzw: ^0.17.0
  execa: ^9.6.1
  fast-xml-parser: ^5.8.0
  happy-dom: ^20.10.2
  nuxt: ^4.4.8
  nuxt-i18n-micro: ^3.18.2
  nuxt-site-config: ^4.0.8
  nuxtseo-layer-devtools: ^5.2.6
  nuxtseo-shared: ^5.2.6
  ofetch: ^1.5.1
  pathe: ^2.0.3
  pkg-types: ^2.3.1
  radix3: ^1.1.2
  semver: ^7.8.4
  sirv: ^3.0.2
  std-env: ^4.1.0
  typescript: ^6.0.3
  ufo: ^1.6.4
  ultrahtml: ^1.6.0
  unbuild: ^3.6.1
  vitest: ^4.1.8
  vue: ^3.5.35
  vue-tsc: ^3.3.4
  zod: ^4.4.3

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
trustPolicyIgnoreAfter: 262800
allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  vue-demi: true
