import type { NitroRuntimeCompatibility } from 'nuxtseo-shared/kit'
import { addTemplate, addTypeTemplate, hasNuxtModule } from '@nuxt/kit'
import { renderNitroTypeAugmentations } from 'nuxtseo-shared/kit'

export function registerTypeTemplates(nitroCompatibility: NitroRuntimeCompatibility) {
  const hasRobotsModule = hasNuxtModule('@nuxtjs/robots') || hasNuxtModule('nuxt-simple-robots')
  // Type augmentations for existing modules
  addTypeTemplate({
    filename: 'types/nuxt-sitemap-augments.d.ts',
    getContents: () => {
      const robotsType = hasRobotsModule ? '' : 'robots?: boolean\n'
      const routeRules = `${robotsType}sitemap?: SitemapItemDefaults | false`
      const runtimeHooks = `'sitemap:index-resolved': (ctx: SitemapIndexRenderCtx<${nitroCompatibility.eventType}>) => void | Promise<void>
'sitemap:input': (ctx: SitemapInputCtx<${nitroCompatibility.eventType}>) => void | Promise<void>
'sitemap:resolved': (ctx: SitemapRenderCtx<${nitroCompatibility.eventType}>) => void | Promise<void>
'sitemap:output': (ctx: SitemapOutputHookCtx<${nitroCompatibility.eventType}>) => void | Promise<void>
'sitemap:sources': (ctx: SitemapSourcesHookCtx<${nitroCompatibility.eventType}>) => void | Promise<void>
'sitemap:sitemaps-resolved': (ctx: SitemapsResolvedCtx<${nitroCompatibility.eventType}>) => void | Promise<void>`
      const nitroTypes = renderNitroTypeAugmentations(nitroCompatibility, {
        nitroInterfaces: {
          PrerenderRoute: '_sitemap?: SitemapUrl',
        },
        routeConfig: routeRules,
        routeRules,
        runtimeHooks,
      })
      return `// Generated by @nuxtjs/sitemap
/// <reference path="./nuxt-sitemap-virtual.d.ts" />
import type { SitemapUrl, SitemapItemDefaults, SitemapIndexRenderCtx, SitemapInputCtx, SitemapRenderCtx, SitemapOutputHookCtx, SitemapSourcesHookCtx, SitemapsResolvedCtx } from '@nuxtjs/sitemap'

${nitroTypes}

declare module 'vue-router' {
  interface RouteMeta {
    sitemap?: SitemapItemDefaults | false
  }
}

declare module '#app' {
  interface PageMeta {
    sitemap?: SitemapItemDefaults | false
  }
}

declare module 'nuxt/app' {
  interface PageMeta {
    sitemap?: SitemapItemDefaults | false
  }
}

export {}
`
    },
  }, {
    nitro: true,
    node: true,
    nuxt: true,
  })

  // Type definitions for virtual modules
  addTemplate({
    filename: 'types/nuxt-sitemap-virtual.d.ts',
    getContents: () => `declare module '#sitemap-virtual/read-sources.mjs' {
  export function readSourcesFromFilesystem(filename: string): Promise<any | null>
}

declare module '#sitemap-virtual/global-sources.mjs' {
  import type { SitemapSourceBase, SitemapSourceResolved } from '#sitemap/types'

  export const sources: (SitemapSourceBase | SitemapSourceResolved)[]
}

declare module '#sitemap-virtual/child-sources.mjs' {
  import type { SitemapSourceBase, SitemapSourceResolved } from '#sitemap/types'

  export const sources: Record<string, (SitemapSourceBase | SitemapSourceResolved)[]>
}

declare module '#sitemap/content-filters' {
  export const filters: Map<string, (entry: any) => boolean>
}

declare module '#sitemap/content-on-url' {
  export const onUrlFns: Map<string, (url: Record<string, unknown>, entry: any, collection: string) => void>
}
`,
  })
}
