name: CI

on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    uses: harlan-zw/nuxt-seo/.github/workflows/reusable-ci.yml@main
