name: CI

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: harlan-zw/nuxt-seo/.github/workflows/reusable-ci.yml@09760efb0ffeac9f477673725c1c2f1fc8b1b049
    with:
      test-command: pnpm build && pnpm test
      node-version: 22.22.3
